### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by chawdamrunal** [TROUBLE-1/codeza#1]
python codeza.py 
Traceback (most recent call last):
  File "codeza.py", line 25, in <module>
    from concurrent.futures import ThreadPoolExecutor, as_completed

**Comment by TROUBLE-1** [comment]
> Your system does not have some python modules installed I have uploaded a txt file in my repository you can use that to install required modules

#### Run the following commands
```wget https://raw.githubusercontent.com/TROUBLE-1/codeza/master/requirements.txt```
```sudo pip install -r requirements.txt```
